-- MySQL Script generated by MySQL Workbench
-- 06/29/17 16:28:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `rut_paciente` INT NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `ape_pat` VARCHAR(45) NULL,
  `ape_mat` VARCHAR(45) NULL,
  `sexo` CHAR(1) NULL,
  `direccion` VARCHAR(100) NULL,
  `telefono` INT NULL,
  PRIMARY KEY (`rut_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medico` (
  `rut_medico` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `ape_pat` VARCHAR(45) NULL,
  `ape_mat` VARCHAR(45) NULL,
  `especialidad` VARCHAR(45) NULL,
  `valor_consulta` VARCHAR(45) NULL,
  PRIMARY KEY (`rut_medico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consulta` (
  `idConsulta` INT NOT NULL AUTO_INCREMENT,
  `fecha_atencion` DATETIME NULL,
  `rut_paciente` INT NULL,
  `rut_medico` INT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idConsulta`),
  INDEX `rut_medico_idx` (`rut_medico` ASC),
  INDEX `rut_paciente_idx` (`rut_paciente` ASC),
  CONSTRAINT `rut_medico`
    FOREIGN KEY (`rut_medico`)
    REFERENCES `mydb`.`Medico` (`rut_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rut_paciente`
    FOREIGN KEY (`rut_paciente`)
    REFERENCES `mydb`.`Paciente` (`rut_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
