-- MySQL Script generated by MySQL Workbench
-- Fri Jul  7 09:30:04 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `rut_paciente` INT NOT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `ape_pat` VARCHAR(45) NULL DEFAULT NULL,
  `ape_mat` VARCHAR(45) NULL DEFAULT NULL,
  `sexo` CHAR(1) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  PRIMARY KEY (`rut_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medico` (
  `rut_medico` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `ape_pat` VARCHAR(45) NULL DEFAULT NULL,
  `ape_mat` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_contratacion` DATETIME NULL,
  `especialidad` VARCHAR(45) NULL DEFAULT NULL,
  `valor_consulta` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`rut_medico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consulta` (
  `idConsulta` INT NOT NULL AUTO_INCREMENT,
  `fecha_atencion` DATETIME NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idConsulta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Privilegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Privilegio` (
  `idPrivilegio` INT NOT NULL,
  `tipoPrivilegio` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPrivilegio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `idPrivilegio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`, `usuario`, `contrasena`),
  INDEX `idPrivilegio_idx` (`idPrivilegio` ASC),
  CONSTRAINT `idPrivilegio`
    FOREIGN KEY (`idPrivilegio`)
    REFERENCES `mydb`.`Privilegio` (`idPrivilegio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente_has_Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente_has_Consulta` (
  `Paciente_rut_paciente` INT NOT NULL,
  `Consulta_idConsulta` INT NOT NULL,
  PRIMARY KEY (`Paciente_rut_paciente`, `Consulta_idConsulta`),
  INDEX `fk_Paciente_has_Consulta_Consulta1_idx` (`Consulta_idConsulta` ASC),
  INDEX `fk_Paciente_has_Consulta_Paciente1_idx` (`Paciente_rut_paciente` ASC),
  CONSTRAINT `fk_Paciente_has_Consulta_Paciente1`
    FOREIGN KEY (`Paciente_rut_paciente`)
    REFERENCES `mydb`.`Paciente` (`rut_paciente`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_has_Consulta_Consulta1`
    FOREIGN KEY (`Consulta_idConsulta`)
    REFERENCES `mydb`.`Consulta` (`idConsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medico_has_Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medico_has_Consulta` (
  `Medico_rut_medico` INT NOT NULL,
  `Consulta_idConsulta` INT NOT NULL,
  PRIMARY KEY (`Medico_rut_medico`, `Consulta_idConsulta`),
  INDEX `fk_Medico_has_Consulta_Consulta1_idx` (`Consulta_idConsulta` ASC),
  INDEX `fk_Medico_has_Consulta_Medico1_idx` (`Medico_rut_medico` ASC),
  CONSTRAINT `fk_Medico_has_Consulta_Medico1`
    FOREIGN KEY (`Medico_rut_medico`)
    REFERENCES `mydb`.`Medico` (`rut_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_has_Consulta_Consulta1`
    FOREIGN KEY (`Consulta_idConsulta`)
    REFERENCES `mydb`.`Consulta` (`idConsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Paciente`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Paciente` (`rut_paciente`, `nombres`, `ape_pat`, `ape_mat`, `sexo`, `direccion`, `telefono`) VALUES (93047052, 'Jacob', 'Olivares', 'Fuentes', 'M', 'Nueva 4 Sur', 982396971);
INSERT INTO `mydb`.`Paciente` (`rut_paciente`, `nombres`, `ape_pat`, `ape_mat`, `sexo`, `direccion`, `telefono`) VALUES (72978218, 'Juana', 'Arancibia', 'Penna', 'F', 'Av Brasil 3982', 974634363);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Medico`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Medico` (`rut_medico`, `nombres`, `ape_pat`, `ape_mat`, `fecha_contratacion`, `especialidad`, `valor_consulta`) VALUES (191286200, 'Jacob', 'Olivares', 'Espinoza', '2017-07-04 11:11:00', 'Cardiologo', '25000');
INSERT INTO `mydb`.`Medico` (`rut_medico`, `nombres`, `ape_pat`, `ape_mat`, `fecha_contratacion`, `especialidad`, `valor_consulta`) VALUES (197472138, 'Mariapaz', 'Silva', 'Guzman', '2017-07-04 11:11:00', 'Neurologo', '25000');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Consulta`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Consulta` (`idConsulta`, `fecha_atencion`, `estado`) VALUES (1, '2017-07-04 11:11:00', 'Agendada');
INSERT INTO `mydb`.`Consulta` (`idConsulta`, `fecha_atencion`, `estado`) VALUES (2, '2017-07-04 11:11:00', 'Anulada');
INSERT INTO `mydb`.`Consulta` (`idConsulta`, `fecha_atencion`, `estado`) VALUES (3, '2017-07-04 11:11:00', 'Realizada');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Privilegio`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Privilegio` (`idPrivilegio`, `tipoPrivilegio`) VALUES (1, 'Administrador');
INSERT INTO `mydb`.`Privilegio` (`idPrivilegio`, `tipoPrivilegio`) VALUES (2, 'Director');
INSERT INTO `mydb`.`Privilegio` (`idPrivilegio`, `tipoPrivilegio`) VALUES (3, 'Secretaria');
INSERT INTO `mydb`.`Privilegio` (`idPrivilegio`, `tipoPrivilegio`) VALUES (4, 'Paciente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Usuario` (`idUsuario`, `usuario`, `contrasena`, `idPrivilegio`) VALUES (1, 'jacob', '202cb962ac59075b964b07152d234b70', 1);
INSERT INTO `mydb`.`Usuario` (`idUsuario`, `usuario`, `contrasena`, `idPrivilegio`) VALUES (2, 'director', '3d4e992d8d8a7d848724aa26ed7f4176', 2);
INSERT INTO `mydb`.`Usuario` (`idUsuario`, `usuario`, `contrasena`, `idPrivilegio`) VALUES (3, 'secretaria', 'fd09accffacf03d7393c2a23a9601b43', 3);
INSERT INTO `mydb`.`Usuario` (`idUsuario`, `usuario`, `contrasena`, `idPrivilegio`) VALUES (4, 'paciente', 'd243800a7d0ba0f87081bcdd832bb05f', 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Paciente_has_Consulta`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Paciente_has_Consulta` (`Paciente_rut_paciente`, `Consulta_idConsulta`) VALUES (93047052, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Medico_has_Consulta`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Medico_has_Consulta` (`Medico_rut_medico`, `Consulta_idConsulta`) VALUES (191286200, 1);

COMMIT;

